from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^$', views.home_view,
        name='home'),
    url(r'^notaslista$', views.NotaListView.as_view(),
        name='notas_lista'),
    url(r'^newnota$', views.CreateNotaView.as_view(),
        name='notas_new'),
    url(r'^editnota/(?P<pk>\d+)$', views.UpdateNotaView.as_view(),
        name='notas_edit'),
    url(r'^deletenota/(?P<pk>\d+)$', views.DeleteNotaView.as_view(),
        name='notas_delete'),
    url(r'^nota/(?P<pk>\d+)$', views.NotaView.as_view(),
        name='notas_view'),
    url(r'^admin/userslista$', views.UserListView.as_view(),
        name='users_lista'),
    url(r'^admin/newuser$', views.CreateUserView.as_view(),
        name='users_new'),
    url(r'^admin/edituser/(?P<pk>\d+)$', views.UpdateUserView.as_view(),
        name='users_edit'),
    url(r'^admin/deleteuser/(?P<pk>\d+)$', views.DeleteUserView.as_view(),
        name='users_delete'),
    url(r'^amin/users/(?P<pk>\d+)$', views.UserView.as_view(),
        name='users_view'),
    url(r'^login$', views.Login.as_view(),
        name='login'),
    url(r'^logout$', views.logout_view,
        name='logout'),
    url(r'^change-password/$', views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^change-password/done/$', auth_views.password_change_done,
        {'template_name': 'registration/pwd_change_done.html'},
        name='password_change_done'),
]
